version: '2.2'

services:
  podsync:
    container_name: podsync
    image: mxpv/podsync:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./data:/data/
      - ./config.toml:/app/config.toml
